---

- name: Creates Cantaloupe directory
  file:
    path: /opt/cantaloupe
    state: directory
    owner: tomcat
    group: tomcat
    mode: 2775

- name: Creates Fits directory
  file:
    path: /opt/fits
    state: directory
    owner: tomcat
    group: tomcat
    mode: 2775

- name: Creates Cantaloupe cache directory
  file:
    path: /var/cache/cantaloupe
    state: directory
    owner: tomcat
    group: tomcat
    mode: 2775

- name: Creates Fits directory
  file:
    path: /var/log/cantaloupe
    state: directory
    owner: tomcat
    group: tomcat
    mode: 2775

- name: Template systemd Tomcat9 service
  template:
    src: tomcat9.service.j2
    dest: /etc/systemd/system/tomcat9.service

- name: Reload systemd services
  command: "systemctl daemon-reload"

